#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FutsalManager.Droid.Resource", IsApplication=true)]

namespace FutsalManager.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FutsalManager.Domain.Resource.String.ApplicationName = global::FutsalManager.Droid.Resource.String.ApplicationName;
			global::FutsalManager.Domain.Resource.String.Hello = global::FutsalManager.Droid.Resource.String.Hello;
			global::FutsalManager.Persistence.Resource.String.ApplicationName = global::FutsalManager.Droid.Resource.String.ApplicationName;
			global::FutsalManager.Persistence.Resource.String.Hello = global::FutsalManager.Droid.Resource.String.Hello;
			global::SQLite.Resource.String.ApplicationName = global::FutsalManager.Droid.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::FutsalManager.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int position_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bobai = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bobailogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_new = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_refresh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_save = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070030
			public const int actionDeletePlayer = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int actionPlayerRefresh = 2131165234;
			
			// aapt resource value: 0x7f07002f
			public const int actionSavePlayer = 2131165231;
			
			// aapt resource value: 0x7f070033
			public const int actionSaveTournament = 2131165235;
			
			// aapt resource value: 0x7f070004
			public const int adminButton = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int ageEditText = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int birthDateTextView = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int button3 = 2131165187;
			
			// aapt resource value: 0x7f070029
			public const int championEditText = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int championTextView = 2131165224;
			
			// aapt resource value: 0x7f070020
			public const int checkBox1 = 2131165216;
			
			// aapt resource value: 0x7f07002a
			public const int createTournamentButton = 2131165226;
			
			// aapt resource value: 0x7f070015
			public const int deletePlayerButton = 2131165205;
			
			// aapt resource value: 0x7f07002d
			public const int deleteTournamentButton = 2131165229;
			
			// aapt resource value: 0x7f070019
			public const int goalTextView = 2131165209;
			
			// aapt resource value: 0x7f070005
			public const int imageView1 = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout2 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout3 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout4 = 2131165195;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout5 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout6 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int linearLayout7 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int linearLayout8 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayout9 = 2131165214;
			
			// aapt resource value: 0x7f07002c
			public const int manageTournamentButton = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int masterData = 2131165230;
			
			// aapt resource value: 0x7f07000f
			public const int nameEditText = 2131165199;
			
			// aapt resource value: 0x7f070017
			public const int nameTextView = 2131165207;
			
			// aapt resource value: 0x7f070031
			public const int newPlayer = 2131165233;
			
			// aapt resource value: 0x7f070007
			public const int newTournamentButton = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int pickDatePlayerButton = 2131165202;
			
			// aapt resource value: 0x7f070025
			public const int pickDateTournamentButton = 2131165221;
			
			// aapt resource value: 0x7f070001
			public const int playerButton = 2131165185;
			
			// aapt resource value: 0x7f070021
			public const int playerTourView = 2131165217;
			
			// aapt resource value: 0x7f070010
			public const int positionSpinner = 2131165200;
			
			// aapt resource value: 0x7f070018
			public const int positionTextView = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int relativeLayout1 = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int savePlayerButton = 2131165204;
			
			// aapt resource value: 0x7f07000e
			public const int scrollView1 = 2131165198;
			
			// aapt resource value: 0x7f07001f
			public const int spinner1 = 2131165215;
			
			// aapt resource value: 0x7f07002b
			public const int startEndTournamentButton = 2131165227;
			
			// aapt resource value: 0x7f070027
			public const int statusEditText = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int statusTextView = 2131165222;
			
			// aapt resource value: 0x7f070006
			public const int textView1 = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int textView2 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int textView3 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textView4 = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int tournamentButton = 2131165186;
			
			// aapt resource value: 0x7f070024
			public const int tournamentDateEditText = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int tournamentLinearLayout = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int tournamentScrollView = 2131165218;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdminMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MatchUpdate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PlayerDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlayerListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlayerMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PlayerPerWeek = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PlayerSelector = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PlayerTourList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SelectWhiteTeam = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TournamentSetup = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int PlayerDetailMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int PlayerListViewMenu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int TournamentSetupMenu = 2131099651;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int position_prompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
