#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FutsalManager.Droid.Resource", IsApplication=true)]

namespace FutsalManager.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FutsalManager.Domain.Resource.String.ApplicationName = global::FutsalManager.Droid.Resource.String.ApplicationName;
			global::FutsalManager.Domain.Resource.String.Hello = global::FutsalManager.Droid.Resource.String.Hello;
			global::FutsalManager.Persistence.Resource.String.ApplicationName = global::FutsalManager.Droid.Resource.String.ApplicationName;
			global::FutsalManager.Persistence.Resource.String.Hello = global::FutsalManager.Droid.Resource.String.Hello;
			global::SQLite.Resource.String.ApplicationName = global::FutsalManager.Droid.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::FutsalManager.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int position_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_delete = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_refresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070015
			public const int actionDeletePlayer = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int actionPlayerRefresh = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int actionSavePlayer = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int actionSaveTournament = 2131165208;
			
			// aapt resource value: 0x7f07000c
			public const int ageEditText = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int birthDateTextView = 2131165193;
			
			// aapt resource value: 0x7f070012
			public const int dateTextView = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int goalTextView = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int maintainPlayer = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int nameEditText = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int nameTextView = 2131165198;
			
			// aapt resource value: 0x7f070016
			public const int newPlayer = 2131165206;
			
			// aapt resource value: 0x7f070001
			public const int newTournamentButton = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int pickDateButton = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int playerTourView = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int positionSpinner = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int positionTextView = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int relativeLayout1 = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int scrollView1 = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int textView3 = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int textView4 = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PlayerDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PlayerListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PlayerTourList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TournamentSetup = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int PlayerDetailMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int PlayerListViewMenu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int TournamentSetupMenu = 2131099651;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int position_prompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
